{% set name = "napari-correct-drift" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-correct-drift-{{ version }}.tar.gz
  sha256: a3d3f1094ba9691e1e581446a8aa2c49824b8dc8430425d2dd4a885c333538ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dask-core
    - napari
    - numpy
    - pandas
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_correct_drift
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-correct-drift
  summary: Drift correction 2D/3D for Napari similar to Fijis Correct 3D drift
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/sommerc/napari-correct-drift

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
